'use strict';

const ActionTypes = {
    CHANGE: 'CHANGE',
    RECEIVE_DATA: 'RECEIVE_DATA',
    RECEIVE_API_ERROR: 'RECEIVE_API_ERROR',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',
    SET_USER_INPUT: 'SET_USER_INPUT',
    SET_ACTIVE_SORT: 'SET_ACTIVE_SORT',
    INITIALIZE: 'INITIALIZE'
};

export default ActionTypes;