'use strict';

const ActionTypes = {
    CHANGE: 'CHANGE',
    USERS_INFO_RECIEVE_BEFORE: 'USERS_INFO_RECIEVE_BEFORE',
    USERS_INFO_RECIEVE: 'USERS_INFO_RECIEVE',
    USERS_INFO_RECIEVE_ERROR: 'USERS_INFO_RECIEVE_ERROR',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',
    SET_USER_INPUT: 'SET_USER_INPUT',
    SET_ACTIVE_SORT: 'SET_ACTIVE_SORT',
    INITIALIZE: 'INITIALIZE'
};

export default ActionTypes;